/** General skill catalogue offered when posting a role, grouped loosely by discipline. */
export const GENERAL_SKILLS = [
  // Sales
  "Cold calling",
  "Lead generation",
  "Negotiation",
  "Enterprise sales",
  "Account management",
  "Sales prospecting",
  "HubSpot",
  "Salesforce",
  // Marketing
  "Digital marketing",
  "Social media marketing",
  "Content writing",
  "Copywriting",
  "SEO",
  "Email marketing",
  "Google Ads",
  "Facebook Ads",
  "Marketing strategy",
  // Admin & support
  "Virtual assistance",
  "Data entry",
  "Customer service",
  "Calendar management",
  "Email management",
  "Project management",
  "Bookkeeping",
  "Microsoft Excel",
  "Google Workspace",
  // Design & creative
  "Graphic design",
  "UI/UX design",
  "Figma",
  "Adobe Photoshop",
  "Video editing",
  "Canva",
  // Engineering
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "WordPress",
  "Shopify",
  "QA testing",
  // General
  "Communication",
  "Research",
  "Problem solving",
  "Time management",
] as const;
