import {
  MdAdd,
  MdArrowForward,
  MdArrowUpward,
  MdBookmark,
  MdChecklist,
  MdDragIndicator,
  MdOutlineAddTask,
  MdOutlineHourglassEmpty,
  MdHourglassTop,
  MdOutlineSchedule,
  MdOutlineGridView,
  MdOutlineViewKanban,
  MdOutlineViewList,
  MdTaskAlt,
  MdUndo,
  MdBorderColor,
  MdCall,
  MdCheck,
  MdCheckCircle,
  MdClose,
  MdContentCopy,
  MdDeleteOutline,
  MdDoneAll,
  MdGavel,
  MdHistory,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardDoubleArrowLeft,
  MdLockOutline,
  MdLogout,
  MdMoreHoriz,
  MdMoreVert,
  MdNorthEast,
  MdOutlineAssignment,
  MdOutlineAttachFile,
  MdOutlineBookmarkBorder,
  MdOutlineBusiness,
  MdOutlineCardMembership,
  MdOutlineCases,
  MdOutlineChatBubbleOutline,
  MdOutlineCheckCircle,
  MdOutlineCreditCard,
  MdOutlineDashboard,
  MdOutlineDescription,
  MdOutlineEventNote,
  MdOutlineFlag,
  MdOutlineHome,
  MdOutlineInfo,
  MdOutlineInsertChart,
  MdOutlineLocationOn,
  MdOutlineNotes,
  MdOutlineNotificationsNone,
  MdOutlinePeople,
  MdOutlinePersonOutline,
  MdOutlineReceiptLong,
  MdOutlineSecurity,
  MdOutlineSettings,
  MdOutlineTrackChanges,
  MdOutlineVideoCall,
  MdOutlineVideocam,
  MdOutlineViewCarousel,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdOutlineWallet,
  MdOutlineExplore,
  MdOutlinePeopleOutline,
  MdOutlinePayment,
  MdOutlineWorkOutline,
  MdOutlineDownload,
  MdOutlinePictureAsPdf,
  MdOutlineCalendarToday,
  MdPersonOutline,
  MdPlayCircleFilled,
  MdSearch,
  MdStar,
  MdTrendingUp,
  MdWarningAmber,
  MdWorkOutline,
  MdArrowDownward,
  MdCode,
  MdFilterList,
  MdLink,
  MdOutlineAdminPanelSettings,
  MdOutlineArchive,
  MdOutlineArticle,
  MdOutlineBlock,
  MdOutlineBuild,
  MdOutlineCalendarMonth,
  MdOutlineCampaign,
  MdOutlineCategory,
  MdOutlineDiamond,
  MdOutlineEditCalendar,
  MdOutlineFolder,
  MdOutlineGroups,
  MdOutlineInbox,
  MdOutlineOpenWith,
  MdOutlinePalette,
  MdOutlinePersonOff,
  MdOutlineRateReview,
  MdOutlineScience,
  MdOutlineSell,
  MdOutlineSpeed,
  MdOutlineStackedBarChart,
  MdOutlineTaskAlt,
  MdOutlineUnarchive,
  MdOutlineViewAgenda,
  MdOutlineViewTimeline,
  MdRefresh,
  MdSort,
  MdVerticalAlignBottom,
  MdVerticalAlignTop,
} from "react-icons/md";
import type { IconType } from "react-icons";

/** Google Material Design icons. */
export const ICONS = {
  // rail — admin
  home: MdOutlineHome,
  users: MdOutlinePeople,
  roles: MdWorkOutline,
  disputes: MdGavel,
  subscriptions: MdOutlineCardMembership,
  billing: MdOutlineReceiptLong,
  content: MdOutlineViewCarousel,
  marketing: MdTrendingUp,
  settings: MdOutlineSettings,
  // submenu — admin
  dashboard: MdOutlineDashboard,
  chart: MdOutlineInsertChart,
  business: MdOutlineBusiness,
  person: MdPersonOutline,
  edit: MdBorderColor,
  history: MdHistory,
  // rail + submenu — independent
  contracts: MdOutlineCases,
  wallet: MdOutlineWallet,
  bell: MdOutlineNotificationsNone,
  messages: MdOutlineChatBubbleOutline,
  applications: MdOutlineAssignment,
  saved: MdOutlineBookmarkBorder,
  interviews: MdOutlineEventNote,
  document: MdOutlineDescription,
  account: MdOutlinePersonOutline,
  security: MdOutlineSecurity,
  card: MdOutlineCreditCard,
  logout: MdLogout,
  // controls
  collapse: MdKeyboardDoubleArrowLeft,
  search: MdSearch,
  chevron: MdKeyboardArrowDown,
  chevronLeft: MdKeyboardArrowLeft,
  chevronRight: MdKeyboardArrowRight,
  close: MdClose,
  moreH: MdMoreHoriz,
  moreV: MdMoreVert,
  add: MdAdd,
  check: MdCheck,
  checkCircle: MdCheckCircle,
  checkCircleOutline: MdOutlineCheckCircle,
  trash: MdDeleteOutline,
  info: MdOutlineInfo,
  warning: MdWarningAmber,
  arrowForward: MdArrowForward,
  arrowUp: MdArrowUpward,
  northEast: MdNorthEast,
  attach: MdOutlineAttachFile,
  call: MdCall,
  video: MdOutlineVideocam,
  doneAll: MdDoneAll,
  copy: MdContentCopy,
  flag: MdOutlineFlag,
  bookmark: MdBookmark,
  work: MdOutlineWorkOutline,
  star: MdStar,
  notes: MdOutlineNotes,
  explore: MdOutlineExplore,
  people: MdOutlinePeopleOutline,
  payment: MdOutlinePayment,
  workOutline: MdOutlineWorkOutline,
  lock: MdLockOutline,
  visibility: MdOutlineVisibility,
  visibilityOff: MdOutlineVisibilityOff,
  download: MdOutlineDownload,
  pdf: MdOutlinePictureAsPdf,
  calendar: MdOutlineCalendarToday,
  description: MdOutlineDescription,
  target: MdOutlineTrackChanges,
  location: MdOutlineLocationOn,
  play: MdPlayCircleFilled,
  videoAdd: MdOutlineVideoCall,
  // task lists
  clock: MdOutlineSchedule,
  viewList: MdOutlineViewList,
  viewBoard: MdOutlineViewKanban,
  viewGrid: MdOutlineGridView,
  checklist: MdChecklist,
  drag: MdDragIndicator,
  undo: MdUndo,
  hourglass: MdOutlineHourglassEmpty,
  hourglassFilled: MdHourglassTop,
  taskDone: MdTaskAlt,
  addTask: MdOutlineAddTask,
  // the contract workspace: views, toolbar and item actions
  viewCalendar: MdOutlineCalendarMonth,
  viewTimeline: MdOutlineViewTimeline,
  viewWorkload: MdOutlineStackedBarChart,
  filter: MdFilterList,
  sort: MdSort,
  group: MdOutlineViewAgenda,
  archive: MdOutlineArchive,
  unarchive: MdOutlineUnarchive,
  link: MdLink,
  blocked: MdOutlineBlock,
  tag: MdOutlineSell,
  effort: MdOutlineSpeed,
  unassigned: MdOutlinePersonOff,
  moveTo: MdOutlineOpenWith,
  arrowDown: MdArrowDownward,
  toTop: MdVerticalAlignTop,
  toBottom: MdVerticalAlignBottom,
  retry: MdRefresh,
  schedule: MdOutlineEditCalendar,
  inbox: MdOutlineInbox,
  // work types
  typeTask: MdOutlineTaskAlt,
  project: MdOutlineFolder,
  typeMilestone: MdOutlineDiamond,
  typeDesign: MdOutlinePalette,
  typeDevelopment: MdCode,
  typeMarketing: MdOutlineCampaign,
  typeContent: MdOutlineArticle,
  typeResearch: MdOutlineScience,
  typeReview: MdOutlineRateReview,
  typeMeeting: MdOutlineGroups,
  typeAdmin: MdOutlineAdminPanelSettings,
  typeOperations: MdOutlineBuild,
  typeOther: MdOutlineCategory,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof ICONS;
